INSERT INTO public.event (id, century, name, year) VALUES (18, 13, 'Образование Ордена меченосцев.', 1202);
INSERT INTO public.event (id, century, name, year) VALUES (19, 13, 'Битва на реке Калке.', 1223);
INSERT INTO public.event (id, century, name, year) VALUES (20, 13, 'Завоевание монголо-татарами Волжской Болгарии.', 1236);
INSERT INTO public.event (id, century, name, year) VALUES (21, 13, 'Образование Ливонского ордена.', 1237);
INSERT INTO public.event (id, century, name, year) VALUES (22, 13, 'Битва на реке Сити.', 1238);
INSERT INTO public.event (id, century, name, year) VALUES (23, 13, 'Невская битва.', 1240);
INSERT INTO public.event (id, century, name, year) VALUES (24, 13, 'Ледовое побоище.', 1242);
INSERT INTO public.event (id, century, name, year) VALUES (25, 13, 'Образование государства Золотая Орда.', 1243);
INSERT INTO public.event (id, century, name, year) VALUES (26, 13, 'Образование Тверского княжества.', 1247);
INSERT INTO public.event (id, century, name, year) VALUES (27, 13, 'Правление Батыя.', 1255);
INSERT INTO public.event (id, century, name, year) VALUES (28, 13, 'Восстания в русских городах против монголо-татар.', 1262);
INSERT INTO public.event (id, century, name, year) VALUES (29, 13, 'Образование Московского княжества.', 1276);
INSERT INTO public.event (id, century, name, year) VALUES (30, 13, 'Переезд митрополита из Киева во Владимир.', 1299);
INSERT INTO public.event (id, century, name, year) VALUES (31, 14, 'Присоединение Коломны к Москве.', 1301);
INSERT INTO public.event (id, century, name, year) VALUES (32, 14, 'Вхождение Переяславля-Залесского в состав Московского княжества.', 1302);
INSERT INTO public.event (id, century, name, year) VALUES (33, 14, 'Присоединение Можайска к Москве.', 1303);
INSERT INTO public.event (id, century, name, year) VALUES (34, 14, 'Принятие ислама как государственной религии Золотой Орды.', 1310);
INSERT INTO public.event (id, century, name, year) VALUES (35, 14, 'Восстание в Твери против золотоордынцев.', 1327);
INSERT INTO public.event (id, century, name, year) VALUES (36, 14, 'Перенесение центра митрополии в Москву.', 1328);
INSERT INTO public.event (id, century, name, year) VALUES (38, 14, 'Первая победа над золотоордынцами на р.Воже.', 1378);
INSERT INTO public.event (id, century, name, year) VALUES (39, 14, 'Куликовская битва.', 1380);
INSERT INTO public.event (id, century, name, year) VALUES (40, 14, 'Разгром Москвы Тохтамышем.', 1382);
INSERT INTO public.event (id, century, name, year) VALUES (41, 14, 'Кревская уния между Литвой и Польшей.', 1385);
INSERT INTO public.event (id, century, name, year) VALUES (42, 14, 'Присоединение Нижнего Новгорода к Москве.', 1393);
INSERT INTO public.event (id, century, name, year) VALUES (43, 14, 'Разорение Тимуром Золотой Орды.', 1395);
INSERT INTO public.event (id, century, name, year) VALUES (44, 15, 'Грюнвальдская битва.', 1410);
INSERT INTO public.event (id, century, name, year) VALUES (45, 15, 'Образование Казанского ханства.', 1437);
INSERT INTO public.event (id, century, name, year) VALUES (46, 15, 'Флорентийская уния.', 1439);
INSERT INTO public.event (id, century, name, year) VALUES (47, 15, 'Образование Крымского ханства.', 1443);
INSERT INTO public.event (id, century, name, year) VALUES (48, 15, 'Избрание Ионы на русскую митрополию. Автокефалия русской православной церкви.', 1448);
INSERT INTO public.event (id, century, name, year) VALUES (49, 15, 'Падение Византийской империи.', 1453);
INSERT INTO public.event (id, century, name, year) VALUES (50, 15, 'Присоединение к Москве Ярославского княжества.', 1463);
INSERT INTO public.event (id, century, name, year) VALUES (51, 15, 'Сражение на р. Шелони московских и новгородских войск.', 1471);
INSERT INTO public.event (id, century, name, year) VALUES (52, 15, 'Присоединение к Москве Ростова Великого.', 1474);
INSERT INTO public.event (id, century, name, year) VALUES (53, 15, 'Присоединение Новгорода Великого к Москве.', 1478);
INSERT INTO public.event (id, century, name, year) VALUES (54, 15, 'Стояние на р.Угре. Окончательное свержение монголо-татарского ига.', 1480);
INSERT INTO public.event (id, century, name, year) VALUES (55, 15, 'Присоединение Твери к Москве.', 1485);
INSERT INTO public.event (id, century, name, year) VALUES (56, 15, 'Присоединение к Москве Вятской земли.', 1489);
INSERT INTO public.event (id, century, name, year) VALUES (57, 15, 'Судебник Ивана III.', 1497);
INSERT INTO public.event (id, century, name, year) VALUES (58, 16, 'Конец Золотой Орды.', 1502);
INSERT INTO public.event (id, century, name, year) VALUES (59, 16, 'Церковный собор по вопросу о монастырском землевладении (Нил Сорский', 1503);
INSERT INTO public.event (id, century, name, year) VALUES (60, 16, 'Присоединение Пскова к Москве.', 1510);
INSERT INTO public.event (id, century, name, year) VALUES (61, 16, 'Присоединение Смоленска к Москве.', 1514);
INSERT INTO public.event (id, century, name, year) VALUES (62, 16, 'Присоединение Рязанской и Северской земель к Москве.', 1521);
INSERT INTO public.event (id, century, name, year) VALUES (63, 16, 'Восстание в Москве.', 1547);
INSERT INTO public.event (id, century, name, year) VALUES (64, 16, 'Начало созыва Земских соборов.', 1549);
INSERT INTO public.event (id, century, name, year) VALUES (65, 16, 'Судебник Ивана IV.', 1550);
INSERT INTO public.event (id, century, name, year) VALUES (66, 16, 'Стоглавый собор.', 1551);
INSERT INTO public.event (id, century, name, year) VALUES (67, 16, 'Присоединение Казанского ханства к Москве.', 1552);
INSERT INTO public.event (id, century, name, year) VALUES (68, 16, 'Присоединение Астраханского ханства к России.', 1556);
INSERT INTO public.event (id, century, name, year) VALUES (69, 16, 'Разгром Ливонского ордена.', 1561);
INSERT INTO public.event (id, century, name, year) VALUES (70, 16, 'Начало книгопечатания в России. «Апостол».', 1564);
INSERT INTO public.event (id, century, name, year) VALUES (71, 16, 'Люблинская уния. Образование Речи Посполитой.', 1569);
INSERT INTO public.event (id, century, name, year) VALUES (72, 16, 'Поход Ермака в Сибирь.', 1581);
INSERT INTO public.event (id, century, name, year) VALUES (73, 16, 'Ям-Запольское перемирие с Польшей.', 1582);
INSERT INTO public.event (id, century, name, year) VALUES (37, 14, 'Победа литовских войск над ордынцами при Синих Водах. Вхождение Киева в состав Литвы.', 1363);
INSERT INTO public.event (id, century, name, year) VALUES (74, 16, 'Плюсский мир со Швецией.', 1583);
INSERT INTO public.event (id, century, name, year) VALUES (75, 16, 'Учреждение патриаршества. Патриарх Иов.', 1589);
INSERT INTO public.event (id, century, name, year) VALUES (76, 16, 'Смерть царевича Дмитрия в Угличе.', 1591);
INSERT INTO public.event (id, century, name, year) VALUES (77, 16, 'Составление писцовых и переписных книг.', 1592);
INSERT INTO public.event (id, century, name, year) VALUES (78, 16, 'Тявзинский мир со Швецией.', 1595);
INSERT INTO public.event (id, century, name, year) VALUES (79, 16, 'Брестская церковная уния.', 1596);
INSERT INTO public.event (id, century, name, year) VALUES (80, 16, 'Указ о пятилетнем сыске беглых.', 1597);
INSERT INTO public.event (id, century, name, year) VALUES (81, 17, 'Указ о пятнадцатилетнем сыске беглых.', 1607);
INSERT INTO public.event (id, century, name, year) VALUES (82, 17, 'Первое ополчение.', 1611);
INSERT INTO public.event (id, century, name, year) VALUES (83, 17, 'Освобождение от интервентов Москвы народным ополчением под руководством К.Минина и Д.Пожарского.', 1612);
INSERT INTO public.event (id, century, name, year) VALUES (84, 17, 'Избрание М.Ф.Романова на царство.', 1613);
INSERT INTO public.event (id, century, name, year) VALUES (85, 17, 'Столбовский мир со Швецией.', 1617);
INSERT INTO public.event (id, century, name, year) VALUES (86, 17, 'Деулинское перемирие с Польшей.', 1618);
INSERT INTO public.event (id, century, name, year) VALUES (87, 17, 'Зборовский мир.', 1649);
INSERT INTO public.event (id, century, name, year) VALUES (88, 17, 'Начало реформ патриарха Никона. Раскол.', 1651);
INSERT INTO public.event (id, century, name, year) VALUES (89, 17, 'Переяславская Рада.', 1654);
INSERT INTO public.event (id, century, name, year) VALUES (90, 17, 'Кардисский мир со Швецией.', 1661);
INSERT INTO public.event (id, century, name, year) VALUES (91, 17, '«Медный бунт» в Москве.', 1662);
INSERT INTO public.event (id, century, name, year) VALUES (92, 17, 'Новоторговый устав.', 1667);
INSERT INTO public.event (id, century, name, year) VALUES (93, 17, 'Отмена местничества.', 1682);
INSERT INTO public.event (id, century, name, year) VALUES (94, 17, '«Вечный мир» с Польшей.', 1686);
INSERT INTO public.event (id, century, name, year) VALUES (95, 17, 'Открытие Славяно-греко-латинской академии.', 1687);
INSERT INTO public.event (id, century, name, year) VALUES (96, 17, 'Нерчинский договор с Китаем.', 1689);
INSERT INTO public.event (id, century, name, year) VALUES (97, 18, 'Введение нового летосчисления.', 1700);
INSERT INTO public.event (id, century, name, year) VALUES (98, 18, 'Основание Санкт-Петербурга.', 1703);
INSERT INTO public.event (id, century, name, year) VALUES (99, 18, 'Полтавская битва.', 1709);
INSERT INTO public.event (id, century, name, year) VALUES (100, 18, 'Учреждение Сената.', 1711);
INSERT INTO public.event (id, century, name, year) VALUES (101, 18, 'Перенесение столицы в Санкт-Петербург.', 1713);
INSERT INTO public.event (id, century, name, year) VALUES (102, 18, 'Указ о единонаследии.', 1714);
INSERT INTO public.event (id, century, name, year) VALUES (103, 18, 'Победа русского флота у острова Гренгам.', 1720);
INSERT INTO public.event (id, century, name, year) VALUES (104, 18, 'Учреждение Синода.', 1721);
INSERT INTO public.event (id, century, name, year) VALUES (105, 18, 'Табель о рангах.', 1722);
INSERT INTO public.event (id, century, name, year) VALUES (106, 18, 'Открытие Академии наук в Петербурге.', 1725);
INSERT INTO public.event (id, century, name, year) VALUES (107, 18, 'Отмена единонаследия.', 1731);
INSERT INTO public.event (id, century, name, year) VALUES (108, 18, 'Открытие первого русского театра в Ярославле.', 1750);
INSERT INTO public.event (id, century, name, year) VALUES (109, 18, 'Основание Московского университета.', 1755);
INSERT INTO public.event (id, century, name, year) VALUES (110, 18, 'Манифест о вольности дворянства.', 1762);
INSERT INTO public.event (id, century, name, year) VALUES (111, 18, 'Секуляризация церковных имуществ.', 1764);
INSERT INTO public.event (id, century, name, year) VALUES (112, 18, 'Начало выпуска ассигнаций.', 1768);
INSERT INTO public.event (id, century, name, year) VALUES (113, 18, 'Чумной бунт в Москве.', 1771);
INSERT INTO public.event (id, century, name, year) VALUES (114, 18, 'Учреждение о губерниях Российской империи.', 1775);
INSERT INTO public.event (id, century, name, year) VALUES (115, 18, 'Декларация о вооруженном нейтралитете.', 1780);
INSERT INTO public.event (id, century, name, year) VALUES (116, 18, 'Георгиевский трактат. Переход Восточной Грузии; под протекторат России.', 1783);
INSERT INTO public.event (id, century, name, year) VALUES (117, 18, 'Жалованные грамоты дворянству и городам.', 1785);
INSERT INTO public.event (id, century, name, year) VALUES (118, 18, 'Манифест о трехдневной барщине.', 1797);
INSERT INTO public.event (id, century, name, year) VALUES (119, 19, 'Учреждение министерств в России.', 1802);
INSERT INTO public.event (id, century, name, year) VALUES (120, 19, 'Указ о «вольных хлебопашцах».', 1803);
INSERT INTO public.event (id, century, name, year) VALUES (121, 19, 'Сражение при Аустерлице.', 1805);
INSERT INTO public.event (id, century, name, year) VALUES (122, 19, 'Тильзитский мир.', 1807);
INSERT INTO public.event (id, century, name, year) VALUES (123, 19, 'Создание Государственного совета.', 1810);
INSERT INTO public.event (id, century, name, year) VALUES (124, 19, 'Отечественная война.', 1812);
INSERT INTO public.event (id, century, name, year) VALUES (125, 19, '«Битва народов» при Лейпциге.', 1813);
INSERT INTO public.event (id, century, name, year) VALUES (126, 19, 'Венский конгресс.', 1814);
INSERT INTO public.event (id, century, name, year) VALUES (127, 19, 'Восстание в Семеновском полку.', 1820);
INSERT INTO public.event (id, century, name, year) VALUES (128, 19, 'Образование Южного общества.', 1821);
INSERT INTO public.event (id, century, name, year) VALUES (129, 19, 'Образование Северного общества.', 1822);
INSERT INTO public.event (id, century, name, year) VALUES (130, 19, 'Образование Общества соединенных славян.', 1823);
INSERT INTO public.event (id, century, name, year) VALUES (131, 19, 'Восстание декабристов в Петербурге.', 1825);
INSERT INTO public.event (id, century, name, year) VALUES (132, 19, 'Издание «чугунного» цензурного устава.', 1826);
INSERT INTO public.event (id, century, name, year) VALUES (133, 19, 'Строительство железной дороги из Петербурга в Царское Село.', 1837);
INSERT INTO public.event (id, century, name, year) VALUES (134, 19, 'Издание указа об «обязанных крестьянах».', 1842);
INSERT INTO public.event (id, century, name, year) VALUES (135, 19, 'Образование Славянского общества св.Кирилла и Мефодия.', 1845);
INSERT INTO public.event (id, century, name, year) VALUES (136, 19, 'Сражение при Синопе.', 1853);
INSERT INTO public.event (id, century, name, year) VALUES (137, 19, 'Оборона Севастополя.', 1854);
INSERT INTO public.event (id, century, name, year) VALUES (138, 19, 'Подписание Симодского договора России с Японией.', 1855);
INSERT INTO public.event (id, century, name, year) VALUES (139, 19, 'Парижский конгресс.', 1856);
INSERT INTO public.event (id, century, name, year) VALUES (140, 19, 'Пекинский договор России с Китаем.', 1860);
INSERT INTO public.event (id, century, name, year) VALUES (141, 19, 'Отмена крепостного права в России.', 1861);
INSERT INTO public.event (id, century, name, year) VALUES (142, 19, 'Судебная, земская и школьная реформы.', 1864);
INSERT INTO public.event (id, century, name, year) VALUES (143, 19, 'Образование Туркестанского генерал-губернаторства.', 1866);
INSERT INTO public.event (id, century, name, year) VALUES (144, 19, 'Установление вассальной зависимости Бухарского эмирата от России.', 1868);
INSERT INTO public.event (id, century, name, year) VALUES (145, 19, 'Издание «Городового положения».', 1870);
INSERT INTO public.event (id, century, name, year) VALUES (146, 19, 'Создание Союза трех императоров.', 1873);
INSERT INTO public.event (id, century, name, year) VALUES (147, 19, 'Первое «хождение в народ».', 1874);
INSERT INTO public.event (id, century, name, year) VALUES (148, 19, 'Трактат России и Японии о разделе владений на Курильских островах и острове Сахалин.', 1875);
INSERT INTO public.event (id, century, name, year) VALUES (149, 19, 'Второе «хождение в народ».', 1876);
INSERT INTO public.event (id, century, name, year) VALUES (150, 19, 'Оборона Шипкинского перевала.', 1877);
INSERT INTO public.event (id, century, name, year) VALUES (151, 19, 'Подписание Сан-Стефанского мирного договора.', 1878);
INSERT INTO public.event (id, century, name, year) VALUES (152, 19, 'Принятие «Положения о мерах к охранению государственной безопасности и общественного спокойствия».', 1881);
INSERT INTO public.event (id, century, name, year) VALUES (153, 19, 'Перевод крестьян на обязательный выкуп.', 1882);
INSERT INTO public.event (id, century, name, year) VALUES (154, 19, 'Стачка на Никольской мануфактуре Т.С.Морозова в Орехово-Зуеве.', 1885);
INSERT INTO public.event (id, century, name, year) VALUES (155, 19, 'Циркуляр о «кухаркиных детях».', 1887);
INSERT INTO public.event (id, century, name, year) VALUES (156, 19, 'Принятие «Положения о земских начальниках».', 1889);
INSERT INTO public.event (id, century, name, year) VALUES (157, 19, 'Принятие «Положения о губернских и уездных земских учреждениях» (земская контрреформа).', 1890);
INSERT INTO public.event (id, century, name, year) VALUES (158, 19, 'Принятие «Городового положения» (городская контрреформа).', 1892);
INSERT INTO public.event (id, century, name, year) VALUES (159, 19, 'Создание «Союза борьбы за освобождение рабочего класса».', 1895);
INSERT INTO public.event (id, century, name, year) VALUES (160, 19, 'Первая всеобщая перепись населения в России.', 1897);
INSERT INTO public.event (id, century, name, year) VALUES (161, 19, 'I съезд РСДРП.', 1898);
INSERT INTO public.event (id, century, name, year) VALUES (162, 20, 'Создание газеты «Искра».', 1900);
INSERT INTO public.event (id, century, name, year) VALUES (163, 20, '«Обуховская оборона».', 1901);
INSERT INTO public.event (id, century, name, year) VALUES (164, 20, 'Объединение неонароднических кружков. Создание «Партии социалистов-революционеров».', 1902);
INSERT INTO public.event (id, century, name, year) VALUES (165, 20, 'Создание «Союза земцев-конституционалистов».', 1903);
INSERT INTO public.event (id, century, name, year) VALUES (166, 20, 'Нападение японских кораблей на русские эскадры в Порт-Артуре и Чемульпо.', 1904);
INSERT INTO public.event (id, century, name, year) VALUES (167, 20, 'Вооруженное восстание в Москве.', 1905);
INSERT INTO public.event (id, century, name, year) VALUES (168, 20, 'Указ о выходе крестьян из общины.', 1906);
INSERT INTO public.event (id, century, name, year) VALUES (169, 20, 'Роспуск Государственной Думы и принятие нового избирательного закона.', 1907);
INSERT INTO public.event (id, century, name, year) VALUES (170, 20, 'Ленский расстрел.', 1912);
INSERT INTO public.event (id, century, name, year) VALUES (171, 20, 'Галицийская операция русской армии.', 1914);
INSERT INTO public.event (id, century, name, year) VALUES (172, 20, '«Брусиловский прорыв» русских войск.', 1916);
INSERT INTO public.event (id, century, name, year) VALUES (173, 20, 'Отречение Николая II от престола. Образование Временного правительства. Установление двоевластия в России.', 1917);
INSERT INTO public.event (id, century, name, year) VALUES (174, 20, 'Конституция РСФСР.', 1918);
INSERT INTO public.event (id, century, name, year) VALUES (175, 20, 'VIII съезд РКП(б).', 1919);
INSERT INTO public.event (id, century, name, year) VALUES (176, 20, 'X съезд РКП(б), переход к НЭПу.', 1920);
INSERT INTO public.event (id, century, name, year) VALUES (177, 20, 'Образование СССР.', 1922);
INSERT INTO public.event (id, century, name, year) VALUES (178, 20, 'Конституция СССР.', 1924);
INSERT INTO public.event (id, century, name, year) VALUES (179, 20, 'XIV съезд ВКП(б). Курс на индустриализацию.', 1925);
INSERT INTO public.event (id, century, name, year) VALUES (180, 20, 'XV съезд ВКП(б). Курс на коллективизацию.', 1927);
INSERT INTO public.event (id, century, name, year) VALUES (181, 20, 'Начало сплошной коллективизации.', 1929);
INSERT INTO public.event (id, century, name, year) VALUES (182, 20, 'Конституция СССР.', 1936);
INSERT INTO public.event (id, century, name, year) VALUES (183, 20, 'Пакт о ненападении с Германией.', 1939);
INSERT INTO public.event (id, century, name, year) VALUES (184, 20, 'Начало наступления под Москвой.', 1941);
INSERT INTO public.event (id, century, name, year) VALUES (185, 20, 'Капитуляция Геермании.', 1945);
INSERT INTO public.event (id, century, name, year) VALUES (186, 20, 'Создание Совета экономической взаимопомощи (СЭВ).', 1949);
INSERT INTO public.event (id, century, name, year) VALUES (187, 20, 'Избрание Первым секретарем ЦК КПСС Н.С.Хрущева.', 1953);
INSERT INTO public.event (id, century, name, year) VALUES (188, 20, 'Пленум по НТП.', 1955);
INSERT INTO public.event (id, century, name, year) VALUES (189, 20, 'XX съезд КПСС.', 1956);
INSERT INTO public.event (id, century, name, year) VALUES (190, 20, 'Реформа управления гражданской промышленностью. Создание совнархозов.', 1957);
INSERT INTO public.event (id, century, name, year) VALUES (191, 20, 'Визит Н.С. Хрущева в США. 1959-1965', 1959);
INSERT INTO public.event (id, century, name, year) VALUES (192, 20, 'Полет Ю.А.Гагарина в космос.', 1961);
INSERT INTO public.event (id, century, name, year) VALUES (193, 20, 'Карибский кризис.', 1962);
INSERT INTO public.event (id, century, name, year) VALUES (194, 20, 'Избрание Первым секретарем ЦК КПСС Л.И.Брежнева.', 1964);
INSERT INTO public.event (id, century, name, year) VALUES (195, 20, 'XXIV съезд КПСС.', 1970);
INSERT INTO public.event (id, century, name, year) VALUES (196, 20, 'Совещание по безопасности и сотрудничеству в Европе (Хельсинки).', 1975);
INSERT INTO public.event (id, century, name, year) VALUES (197, 20, 'XXV съезд КПСС.', 1976);
INSERT INTO public.event (id, century, name, year) VALUES (198, 20, 'Конституция СССР.', 1977);
INSERT INTO public.event (id, century, name, year) VALUES (199, 20, 'XXVI съезд КПСС.', 1981);
INSERT INTO public.event (id, century, name, year) VALUES (200, 20, 'Принятие Продовольственной программы.', 1982);
INSERT INTO public.event (id, century, name, year) VALUES (201, 20, 'Избрание Генеральным секретарем ЦК КПСС М.С.Горбачева.', 1985);
INSERT INTO public.event (id, century, name, year) VALUES (202, 20, 'XXVII съезд КПСС.', 1986);
INSERT INTO public.event (id, century, name, year) VALUES (203, 20, 'XIX Всесоюзная партконференция.', 1988);
INSERT INTO public.event (id, century, name, year) VALUES (204, 20, 'I Съезд народных депутатов СССР.', 1989);
INSERT INTO public.event (id, century, name, year) VALUES (205, 20, 'III Съезд народных депутатов СССР. Избрание М.С.Горбачева Президентом СССР.', 1990);
INSERT INTO public.event (id, century, name, year) VALUES (206, 20, 'Избрание Б.Н.Ельцина Президентом РСФСР.', 1991);
INSERT INTO public.event (id, century, name, year) VALUES (207, 20, 'Подписание Федеративного договора.', 1992);
INSERT INTO public.event (id, century, name, year) VALUES (208, 20, 'Выборы в Государственную Думу и Совет Федерации. Принятие конституции РФ.', 1993);
INSERT INTO public.event (id, century, name, year) VALUES (209, 20, 'Выборы в VI Государственную Думу.', 1995);
INSERT INTO public.event (id, century, name, year) VALUES (210, 20, 'Выборы Президента Российской Федерации.', 1996);
INSERT INTO public.event (id, century, name, year) VALUES (211, 20, 'Указ о прекращении исполнения полномочий Президента РФ Ельциным Б. Н.', 1999);